package com.nimchat.app

import android.Manifest
import android.app.*
import android.content.*
import android.content.pm.PackageManager
import android.graphics.Color
import android.graphics.Typeface
import android.net.Uri
import android.os.Build
import android.os.Bundle
import android.text.Editable
import android.text.TextWatcher
import android.view.*
import android.view.inputmethod.EditorInfo
import android.widget.*
import androidx.core.app.ActivityCompat
import androidx.core.app.NotificationCompat
import androidx.core.app.NotificationManagerCompat
import androidx.core.content.FileProvider
import io.github.jan.supabase.auth.Auth
import io.github.jan.supabase.auth.auth
import io.github.jan.supabase.auth.signInAnonymously
import io.github.jan.supabase.createSupabaseClient
import io.github.jan.supabase.postgrest.Postgrest
import io.github.jan.supabase.postgrest.from
import io.github.jan.supabase.postgrest.query.Order
import io.github.jan.supabase.realtime.PostgresAction
import io.github.jan.supabase.realtime.Realtime
import io.github.jan.supabase.storage.Storage
import io.github.jan.supabase.storage.storage
import kotlinx.coroutines.*
import kotlinx.coroutines.flow.merge
import kotlinx.serialization.Serializable
import java.io.File
import java.text.SimpleDateFormat
import java.util.*

@Serializable data class NCProfile(val id:String,val username:String,val display_name:String?=null)
@Serializable data class NCMessage(val id:String?=null,val conversation_id:String,val sender_id:String,val body:String?=null,val created_at:String?=null,val updated_at:String?=null,val read_at:String?=null,val attachment_path:String?=null,val attachment_name:String?=null,val attachment_mime:String?=null,val attachment_size:Long?=null)
@Serializable data class NCConversation(val conversation_id:String,val other_user_id:String,val other_username:String,val other_display_name:String?=null,val last_message:String?=null,val last_message_at:String?=null,val unread_count:Long=0)
private val ncSupabase=createSupabaseClient(BuildConfig.SUPABASE_URL,BuildConfig.SUPABASE_KEY){install(Auth);install(Postgrest);install(Realtime);install(Storage)}

class NimChatActivity:Activity(){
 private val scope=CoroutineScope(SupervisorJob()+Dispatchers.Main)
 private val outbox by lazy{NCOutbox(getSharedPreferences("nimchat_outbox",MODE_PRIVATE))}
 private var uid:String?=null;private var username="";private var activeCid:String?=null;private var chatUser="";private var list:LinearLayout?=null;private var scroll:ScrollView?=null;private var rt:Job?=null;private var homeRt:Job?=null;private var fallback:Job?=null;private var cachedConversations=emptyList<NCConversation>();private val failedOutgoing=linkedMapOf<String,NCFailedMessage>();private var refreshQueued=false
 private val channelId="nimchat_messages"
 override fun onCreate(state:Bundle?){super.onCreate(state);createNotificationChannel();uid=ncSupabase.auth.currentUserOrNull()?.id;if(uid==null)showAuth()else loadProfile()}
 override fun onDestroy(){stopAll();scope.cancel();super.onDestroy()}
 private fun base()=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(20,20,20,16);setBackgroundColor(Color.rgb(248,249,251))}
 private fun t(s:String,z:Float,b:Boolean=false)=TextView(this).apply{text=s;textSize=z;setTextColor(Color.rgb(25,28,35));if(b)typeface=Typeface.DEFAULT_BOLD}
 private fun btn(s:String)=Button(this).apply{text=s;isAllCaps=false}
 private fun inp(h:String)=EditText(this).apply{hint=h;textSize=16f;maxLines=1;imeOptions=EditorInfo.IME_ACTION_DONE}
 private fun lp(w:Int=-1,top:Int=0,bottom:Int=0)=LinearLayout.LayoutParams(w,LinearLayout.LayoutParams.WRAP_CONTENT).apply{setMargins(0,top,0,bottom)}
 private fun showAuth(error:String?=null){stopAll();val root=base();root.gravity=Gravity.CENTER_HORIZONTAL;root.addView(t("NimChat",34f,true),lp());root.addView(t("پیام‌رسان سریع و ساده",17f),lp(-1,8,20));if(error!=null)root.addView(t(error,14f).apply{setTextColor(Color.RED)},lp(-1,0,10));val name=inp("نام کاربری (a-z, 0-9, _");root.addView(name,lp(-1,0,10));val enter=btn("ورود به NimChat");root.addView(enter);setContentView(root);enter.setOnClickListener{val u=name.text.toString().trim().lowercase(Locale.ROOT);if(!u.matches(Regex("[a-z0-9_]{2,30}"))){name.error="۲ تا ۳۰ کاراکتر";return@setOnClickListener};enter.isEnabled=false;scope.launch{try{val id=ensureAuthenticated();val p=withTimeout(10000){ncSupabase.from("profiles").select{filter{eq("id",id)}}.decodeSingleOrNull<NCProfile>()};if(p==null)withTimeout(10000){ncSupabase.from("profiles").insert(NCProfile(id,u,u))}else if(p.username!=u)error("این حساب قبلاً با نام کاربری ${p.username} ثبت شده است");uid=id;username=u;showHome()}catch(e:Exception){enter.isEnabled=true;showAuth("ورود ناموفق: ${friendly(e)}")}}}}
 private suspend fun ensureAuthenticated():String{val cached=ncSupabase.auth.currentUserOrNull()?.id;if(cached!=null)return cached;withTimeout(12000){ncSupabase.auth.signInAnonymously()};return ncSupabase.auth.currentUserOrNull()?.id?:error("احراز هویت ناموفق")}
 private fun loadProfile()=scope.launch{try{val id=uid?:return@launch;val p=withTimeout(10000){ncSupabase.from("profiles").select{filter{eq("id",id)}}.decodeSingleOrNull<NCProfile>()};if(p==null)showAuth("پروفایل پیدا نشد")else{username=p.username;showHome()}}catch(e:Exception){showAuth(friendly(e))}}
 private fun showHome(){stopChatOnly();val root=base();val h=LinearLayout(this).apply{gravity=Gravity.CENTER_VERTICAL};h.addView(t("NimChat",28f,true),LinearLayout.LayoutParams(0,-2,1f));h.addView(btn("پروفایل").apply{setOnClickListener{showProfileDialog()}});h.addView(btn("خروج").apply{setOnClickListener{scope.launch{try{withTimeout(5000){ncSupabase.auth.signOut()}}catch(_:Exception){};uid=null;username="";cachedConversations=emptyList();showAuth()}}});root.addView(h,lp(-1,0,10));root.addView(t("سلام $username 👋",19f,true),lp(-1,0,10));val search=inp("جستجوی گفتگو یا نام کاربری");root.addView(search,lp(-1,0,8));val start=btn("＋ شروع گفتگوی جدید");root.addView(start,lp(-1,0,14));start.setOnClickListener{startChatByUsername(search,start)};root.addView(t("گفتگوهای من",19f,true),lp(-1,0,8));val sv=ScrollView(this);val rows=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL};sv.addView(rows);root.addView(sv,LinearLayout.LayoutParams(-1,0,1f));list=rows;setContentView(root);search.addTextChangedListener(object:TextWatcher{override fun beforeTextChanged(s:CharSequence?,st:Int,c:Int,a:Int)=Unit;override fun onTextChanged(s:CharSequence?,st:Int,b:Int,c:Int){renderConversations(rows,s?.toString().orEmpty())};override fun afterTextChanged(e:Editable?)=Unit});scope.launch{loadConversations(rows)};startHomeRealtime()}
 private fun startChatByUsername(input:EditText,button:Button){val u=input.text.toString().trim().lowercase(Locale.ROOT);if(!u.matches(Regex("[a-z0-9_]{2,30}"))){input.error="نام کاربری معتبر نیست";return};button.isEnabled=false;scope.launch{try{val target=withTimeout(10000){ncSupabase.from("profiles").select{filter{eq("username",u)}}.decodeSingleOrNull<NCProfile>()}?:error("کاربر پیدا نشد");val me=uid?:error("جلسه وجود ندارد");if(target.id==me)error("گفتگو با خودت ممکن نیست");val cid=withTimeout(10000){ncSupabase.postgrest.rpc("create_direct_conversation",CreateConversationParams(target.id)).decodeAs<String>()};activeCid=cid;chatUser=target.username;showChat()}catch(e:Exception){Toast.makeText(this@NimChatActivity,friendly(e),Toast.LENGTH_LONG).show()}finally{button.isEnabled=true}}}
 private suspend fun loadConversations(container:LinearLayout){try{cachedConversations=withTimeout(12000){ncSupabase.postgrest.rpc("list_my_conversations").decodeList<NCConversation>()};renderConversations(container,"")}catch(e:Exception){container.removeAllViews();container.addView(t("بارگذاری ناموفق: ${friendly(e)}",14f).apply{setTextColor(Color.RED)})}}
 private fun renderConversations(container:LinearLayout,raw:String){val q=raw.trim().lowercase(Locale.ROOT);val rows=cachedConversations.filter{r->q.isBlank()||r.other_username.lowercase(Locale.ROOT).contains(q)||r.other_display_name.orEmpty().lowercase(Locale.ROOT).contains(q)||r.last_message.orEmpty().lowercase(Locale.ROOT).contains(q)};container.removeAllViews();if(rows.isEmpty()){container.addView(t(if(q.isBlank())"هنوز گفتگویی نداری." else "نتیجه‌ای پیدا نشد",15f),lp(-1,10));return};rows.forEach{r->val item=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(14,12,14,12);setBackgroundColor(Color.WHITE)};val top=LinearLayout(this).apply{gravity=Gravity.CENTER_VERTICAL};top.addView(t(r.other_display_name?.takeIf{it.isNotBlank()}?:r.other_username,17f,true),LinearLayout.LayoutParams(0,-2,1f));if(r.unread_count>0)top.addView(t(" ${r.unread_count} ",13f,true).apply{setTextColor(Color.WHITE);setBackgroundColor(Color.rgb(35,110,210));setPadding(8,3,8,3)});item.addView(top);item.addView(t(r.last_message?.replace("\n"," ")?.take(80)?:"هنوز پیامی ارسال نشده",14f),lp(-1,4));r.last_message_at?.let{item.addView(t(formatTime(it),11f).apply{setTextColor(Color.GRAY)},lp(-1,4))};item.setOnClickListener{activeCid=r.conversation_id;chatUser=r.other_username;showChat()};container.addView(item,lp(-1,0,8))}}
 private fun showChat(){val cid=activeCid?:return;stopChatOnly();val root=base();val header=LinearLayout(this).apply{gravity=Gravity.CENTER_VERTICAL};val back=btn("‹").apply{textSize=28f};header.addView(back,LinearLayout.LayoutParams(54,54));header.addView(t(chatUser,22f,true),LinearLayout.LayoutParams(0,-2,1f));back.setOnClickListener{showHome()};root.addView(header,lp(-1,0,6));val sv=ScrollView(this);val messages=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(4,8,4,8)};sv.addView(messages);root.addView(sv,LinearLayout.LayoutParams(-1,0,1f));list=messages;scroll=sv;val composer=LinearLayout(this).apply{gravity=Gravity.CENTER_VERTICAL};val input=inp("پیام بنویس...").apply{maxLines=4;minLines=1};val send=btn("ارسال");composer.addView(input,LinearLayout.LayoutParams(0,-2,1f));composer.addView(send);root.addView(composer,lp(-1,8));setContentView(root);send.setOnClickListener{sendText(cid,input,send)};input.setOnEditorActionListener{_,a,_->if(a==EditorInfo.IME_ACTION_DONE){send.performClick();true}else false};scope.launch{refreshMessages(cid)};startChatRealtime(cid)}
 private fun sendText(cid:String,input:EditText,button:Button){val body=input.text.toString().trim();if(body.isEmpty())return;if(body.length>4000){input.error="حداکثر ۴۰۰۰ کاراکتر";return};button.isEnabled=false;scope.launch{val me=uid;if(me==null){button.isEnabled=true;return@launch};val id=UUID.randomUUID().toString();try{sendOutgoing(NCMessage(id,cid,me,body));input.text.clear();failedOutgoing.remove(id);outbox.remove(id);refreshMessages(cid)}catch(e:Exception){val failed=NCFailedMessage(id,cid,me,body,friendly(e));failedOutgoing[id]=failed;outbox.save(failed);refreshMessages(cid);Toast.makeText(this@NimChatActivity,"ارسال ناموفق؛ پیام ذخیره شد",Toast.LENGTH_LONG).show()}finally{button.isEnabled=true}}}
 private suspend fun sendOutgoing(message:NCMessage){try{withTimeout(10000){ncSupabase.from("messages").insert(message)}}catch(first:Exception){val existing=try{withTimeout(5000){ncSupabase.from("messages").select{filter{eq("id",message.id?:"")}}.decodeSingleOrNull<NCMessage>()}}catch(_:Exception){null};if(existing?.id==message.id)return;throw first}}
 private fun retryFailedMessage(failed:NCFailedMessage){if(!NimChatRetry.shouldRetry(failed,activeCid?:return))return;val current=failedOutgoing[failed.id]?:return;scope.launch{try{val me=uid?:return@launch;sendOutgoing(NCMessage(current.id,current.conversation_id,me,current.body));failedOutgoing.remove(current.id);outbox.remove(current.id);refreshMessages(current.conversation_id)}catch(e:Exception){val next=current.copy(error=friendly(e));failedOutgoing[current.id]=next;outbox.save(next);refreshMessages(current.conversation_id)}}}
 private fun startChatRealtime(cid:String){rt?.cancel();rt=scope.launch{try{ncSupabase.realtime.connect();val channel=ncSupabase.realtime.channel("chat-$cid");val inserts=channel.postgresChangeFlow<PostgresAction.Insert>(schema="public"){table="messages"};val updates=channel.postgresChangeFlow<PostgresAction.Update>(schema="public"){table="messages"};val deletes=channel.postgresChangeFlow<PostgresAction.Delete>(schema="public"){table="messages"};channel.subscribe();merge(inserts,updates,deletes).collect{queueRefresh(cid)}}catch(_:Exception){}};fallback=scope.launch{while(isActive){delay(6000);if(activeCid==cid)refreshMessages(cid)}}}
 private fun queueRefresh(cid:String){if(refreshQueued)return;refreshQueued=true;scope.launch{delay(150);refreshQueued=false;if(activeCid==cid)refreshMessages(cid)}}
 private suspend fun refreshMessages(cid:String){try{var messages=withTimeout(10000){ncSupabase.from("messages").select{filter{eq("conversation_id",cid)};order("created_at",Order.ASCENDING)}.decodeList<NCMessage>()};if(messages.any{it.sender_id!=uid&&it.read_at==null}){withTimeout(10000){ncSupabase.postgrest.rpc("mark_conversation_read",MarkConversationReadParams(cid))};messages=withTimeout(10000){ncSupabase.from("messages").select{filter{eq("conversation_id",cid)};order("created_at",Order.ASCENDING)}.decodeList<NCMessage>()}};val container=list?:return;failedOutgoing.clear();outbox.loadForConversation(cid).forEach{failedOutgoing[it.id]=it};container.removeAllViews();messages.forEach{addMessage(container,it)};failedOutgoing.values.filter{NimChatRetry.shouldRetry(it,cid)}.forEach{addFailedMessage(container,it)};scroll?.post{scroll?.fullScroll(View.FOCUS_DOWN)}}catch(_:Exception){}}
 private fun addFailedMessage(parent:LinearLayout,failed:NCFailedMessage){val row=LinearLayout(this).apply{gravity=Gravity.END;setPadding(4,4,4,4)};val box=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(15,9,15,8);setBackgroundColor(Color.rgb(255,235,235))};box.addView(t(failed.body,16f));box.addView(t("ارسال نشد: ${failed.error}",11f),lp(-1,3));box.addView(btn("تلاش مجدد").apply{setOnClickListener{retryFailedMessage(failed)}},lp(-1,5));row.addView(box);parent.addView(row)}
 private fun addMessage(parent:LinearLayout,message:NCMessage){val mine=message.sender_id==uid;val row=LinearLayout(this).apply{gravity=if(mine)Gravity.END else Gravity.START;setPadding(4,4,4,4)};val box=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(15,9,15,8);setBackgroundColor(if(mine)Color.rgb(220,235,255)else Color.WHITE)};if(!message.body.isNullOrBlank())box.addView(t(message.body.orEmpty(),16f));if(message.attachment_path!=null)box.addView(btn("📎 ${message.attachment_name?:"فایل"}").apply{setOnClickListener{openAttachment(message)}},lp(-1,5));val meta=LinearLayout(this).apply{gravity=Gravity.END};meta.addView(t(formatTime(message.created_at),10f));if(mine){meta.addView(t(if(message.read_at!=null)" ✓✓ خوانده شد" else " ✓ ارسال شد",9f));meta.addView(btn("⋮").apply{setOnClickListener{messageActions(message)}},LinearLayout.LayoutParams(42,40))};box.addView(meta,lp(-1,3));row.addView(box);parent.addView(row)}
 private fun messageActions(message:NCMessage){val options=if(message.body.isNullOrBlank())arrayOf("حذف پیام","لغو")else arrayOf("ویرایش پیام","حذف پیام","لغو");AlertDialog.Builder(this).setItems(options){_,which->if(message.body.isNullOrBlank()){if(which==0)confirmDelete(message)}else when(which){0->showEditDialog(message);1->confirmDelete(message)}}.show()}
 private fun showEditDialog(message:NCMessage){val field=inp("متن پیام");field.setText(message.body.orEmpty());AlertDialog.Builder(this).setTitle("ویرایش پیام").setView(field).setNegativeButton("لغو",null).setPositiveButton("ذخیره"){_,_->val value=field.text.toString().trim();if(value.isNotEmpty())scope.launch{try{ncSupabase.from("messages").update({set("body",value)}){filter{eq("id",message.id?:"")}};activeCid?.let{refreshMessages(it)}}catch(e:Exception){Toast.makeText(this@NimChatActivity,friendly(e),Toast.LENGTH_LONG).show()}}}.show()}
 private fun confirmDelete(message:NCMessage){AlertDialog.Builder(this).setTitle("حذف پیام").setMessage("این پیام حذف شود؟").setNegativeButton("لغو",null).setPositiveButton("حذف"){_,_->scope.launch{try{ncSupabase.from("messages").delete{filter{eq("id",message.id?:"")}};activeCid?.let{refreshMessages(it)}}catch(e:Exception){Toast.makeText(this@NimChatActivity,friendly(e),Toast.LENGTH_LONG).show()}}}.show()}
 private fun pickAttachment(cid:String){Toast.makeText(this,"پیوست در حال توسعه است",Toast.LENGTH_SHORT).show()}
 private fun openAttachment(message:NCMessage){Toast.makeText(this,"باز کردن فایل در حال توسعه است",Toast.LENGTH_SHORT).show()}
 private fun showProfileDialog(){val field=inp("نام نمایشی");field.setText(username);val dialog=AlertDialog.Builder(this).setTitle("پروفایل").setView(field).setNegativeButton("لغو",null).setPositiveButton("ذخیره",null).create();dialog.setOnShowListener{dialog.getButton(AlertDialog.BUTTON_POSITIVE).setOnClickListener{val id=uid?:return@setOnClickListener;scope.launch{try{ncSupabase.from("profiles").update({set("display_name",field.text.toString().trim())}){filter{eq("id",id)}};dialog.dismiss();showHome()}catch(e:Exception){Toast.makeText(this@NimChatActivity,friendly(e),Toast.LENGTH_LONG).show()}}}};dialog.show()}
 private fun startHomeRealtime(){homeRt?.cancel();homeRt=scope.launch{try{ncSupabase.realtime.connect();val homeId=uid?:"user";val channel=ncSupabase.realtime.channel("home-"+homeId);val inserts=channel.postgresChangeFlow<PostgresAction.Insert>(schema="public"){table="messages"};val updates=channel.postgresChangeFlow<PostgresAction.Update>(schema="public"){table="messages"};val deletes=channel.postgresChangeFlow<PostgresAction.Delete>(schema="public"){table="messages"};channel.subscribe();merge(inserts,updates,deletes).collect{val container=list;if(container!=null)loadConversations(container)}}catch(_:Exception){}}}
 private fun notifyIncoming(record:Map<String,Any?>){val sender=record["sender_id"]?.toString()?:return;if(sender==uid)return;val conversation=record["conversation_id"]?.toString()?:return;if(conversation==activeCid)return;val body=record["body"]?.toString()?.takeIf{it.isNotBlank()}?:"پیام جدید";if(Build.VERSION.SDK_INT>=33&&checkSelfPermission(Manifest.permission.POST_NOTIFICATIONS)!=PackageManager.PERMISSION_GRANTED){ActivityCompat.requestPermissions(this,arrayOf(Manifest.permission.POST_NOTIFICATIONS),2001);return};val n=NotificationCompat.Builder(this,channelId).setSmallIcon(android.R.drawable.ic_dialog_email).setContentTitle("NimChat").setContentText(body).setAutoCancel(true).build();try{NotificationManagerCompat.from(this).notify(conversation.hashCode(),n)}catch(_:SecurityException){}}
 private fun createNotificationChannel(){if(Build.VERSION.SDK_INT>=Build.VERSION_CODES.O){val c=NotificationChannel(channelId,"پیام‌های NimChat",NotificationManager.IMPORTANCE_DEFAULT);getSystemService(NotificationManager::class.java).createNotificationChannel(c)}}
 private fun stopChatOnly(){rt?.cancel();fallback?.cancel();rt=null;fallback=null;refreshQueued=false;try{ncSupabase.realtime.removeAllChannels()}catch(_:Exception){}}
 private fun stopAll(){stopChatOnly();homeRt?.cancel();homeRt=null;try{ncSupabase.realtime.removeAllChannels()}catch(_:Exception){}}
 private fun friendly(e:Exception):String=e.message?.replace(Regex("\\s+")," ")?.take(220)?:"خطای نامشخص"
 private fun formatTime(value:String?):String{if(value.isNullOrBlank())return"";return try{SimpleDateFormat("HH:mm",Locale.getDefault()).format(SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSSX",Locale.US).parse(value)?:return value)}catch(_:Exception){value.take(16).replace("T"," ")}}
}
