package com.nimchat.app

import android.Manifest
import android.app.*
import android.content.*
import android.content.pm.PackageManager
import android.graphics.BitmapFactory
import android.graphics.Color
import android.graphics.Typeface
import android.net.Uri
import android.os.Build
import android.os.Bundle
import android.provider.OpenableColumns
import android.text.Editable
import android.text.TextWatcher
import android.view.*
import android.view.inputmethod.EditorInfo
import android.widget.*
import androidx.core.app.ActivityCompat
import androidx.core.app.NotificationCompat
import androidx.core.app.NotificationManagerCompat
import androidx.core.content.FileProvider
import io.github.jan.supabase.auth.Auth
import io.github.jan.supabase.auth.auth
import io.github.jan.supabase.auth.signInAnonymously
import io.github.jan.supabase.createSupabaseClient
import io.github.jan.supabase.postgrest.Postgrest
import io.github.jan.supabase.postgrest.from
import io.github.jan.supabase.postgrest.query.Order
import io.github.jan.supabase.realtime.PostgresAction
import io.github.jan.supabase.realtime.Realtime
import io.github.jan.supabase.realtime.RealtimeChannel
import io.github.jan.supabase.storage.Storage
import io.github.jan.supabase.storage.createOrContinueUpload
import io.github.jan.supabase.storage.downloadAuthenticatedTo
import kotlinx.coroutines.*
import kotlinx.coroutines.flow.merge
import kotlinx.serialization.Serializable
import java.io.File
import java.util.*

@Serializable data class NCProfile(val id:String,val username:String,val display_name:String?=null,val is_premium:Boolean=false)
@Serializable data class NCMessage(val id:String?=null,val conversation_id:String,val sender_id:String,val body:String?=null,val created_at:String?=null,val updated_at:String?=null,val read_at:String?=null,val attachment_path:String?=null,val attachment_name:String?=null,val attachment_mime:String?=null,val attachment_size:Long?=null)
@Serializable data class NCConversation(val conversation_id:String,val other_user_id:String,val other_username:String,val other_display_name:String?=null,val last_message:String?=null,val last_message_at:String?=null,val unread_count:Long=0)
private val ncSupabase=createSupabaseClient(BuildConfig.SUPABASE_URL,BuildConfig.SUPABASE_KEY){install(Auth);install(Postgrest);install(Realtime);install(Storage)}

class NimChatActivity:Activity(){
 private val scope=CoroutineScope(SupervisorJob()+Dispatchers.Main)
 private val outbox by lazy{NCOutbox(getSharedPreferences("nimchat_outbox",MODE_PRIVATE))}
 private var uid:String?=null;private var username="";private var premium=false;private var activeCid:String?=null;private var chatUser="";private var list:LinearLayout?=null;private var scroll:ScrollView?=null;private var rt:Job?=null;private var homeRt:Job?=null;private var fallback:Job?=null;private var chatChannel:RealtimeChannel?=null;private var homeChannel:RealtimeChannel?=null;private var cachedConversations=emptyList<NCConversation>();private val failedOutgoing=linkedMapOf<String,NCFailedMessage>();private var refreshQueued=false;private var lastUnreadTotal:Long?=null;private val channelId="nimchat_messages";private val pickFile=1001
 override fun onCreate(s:Bundle?){super.onCreate(s);createNotificationChannel();uid=ncSupabase.auth.currentUserOrNull()?.id;if(uid==null)showAuth()else loadProfile()}
 override fun onDestroy(){stopAll();scope.cancel();super.onDestroy()}
 private fun base()=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(20,20,20,16);setBackgroundColor(Color.rgb(248,249,251))}
 private fun t(s:String,z:Float,b:Boolean=false)=TextView(this).apply{text=s;textSize=z;if(b)typeface=Typeface.DEFAULT_BOLD}
 private fun btn(s:String)=Button(this).apply{text=s;isAllCaps=false}
 private fun inp(h:String)=EditText(this).apply{hint=h;textSize=16f;maxLines=1;imeOptions=EditorInfo.IME_ACTION_DONE}
 private fun lp(w:Int=-1,top:Int=0,bottom:Int=0)=LinearLayout.LayoutParams(w,LinearLayout.LayoutParams.WRAP_CONTENT).apply{setMargins(0,top,0,bottom)}
 private fun showAuth(error:String?=null){stopAll();activeCid=null;lastUnreadTotal=null;val root=base();root.gravity=Gravity.CENTER_HORIZONTAL;root.addView(t("NimChat",34f,true),lp());root.addView(t("پیام‌رسان سریع و ساده",17f),lp(-1,8,20));if(error!=null)root.addView(t(error,14f),lp(-1,0,10));val name=inp("نام کاربری (a-z, 0-9, _)");root.addView(name,lp(-1,0,10));val enter=btn("ورود به NimChat");root.addView(enter);setContentView(root);enter.setOnClickListener{val u=name.text.toString().trim().lowercase(Locale.ROOT);if(!u.matches(Regex("[a-z0-9_]{2,30}"))){name.error="۲ تا ۳۰ کاراکتر";return@setOnClickListener};enter.isEnabled=false;scope.launch{try{val id=ensureAuthenticated();val p=withTimeout(10000){ncSupabase.from("profiles").select{filter{eq("id",id)}}.decodeSingleOrNull<NCProfile>()};if(p==null)withTimeout(10000){ncSupabase.from("profiles").insert(NCProfile(id,u,u))}else if(p.username!=u)error("نام کاربری این حساب متفاوت است");uid=id;username=u;premium=p?.is_premium?:false;showHome()}catch(e:Exception){enter.isEnabled=true;showAuth(friendly(e))}}}}
 private suspend fun ensureAuthenticated():String{val c=ncSupabase.auth.currentUserOrNull()?.id;if(c!=null)return c;withTimeout(12000){ncSupabase.auth.signInAnonymously()};return ncSupabase.auth.currentUserOrNull()?.id?:error("احراز هویت ناموفق")}
 private fun loadProfile()=scope.launch{try{val id=uid?:return@launch;val p=withTimeout(10000){ncSupabase.from("profiles").select{filter{eq("id",id)}}.decodeSingleOrNull<NCProfile>()};if(p==null)showAuth("پروفایل پیدا نشد")else{username=p.username;premium=p.is_premium;showHome()}}catch(e:Exception){showAuth(friendly(e))}}
 private fun showHome(){stopChatOnly();activeCid=null;val root=base();val h=LinearLayout(this).apply{gravity=Gravity.CENTER_VERTICAL};h.addView(t("NimChat",28f,true),LinearLayout.LayoutParams(0,-2,1f));h.addView(btn("پروفایل").apply{setOnClickListener{showProfileDialog()}});h.addView(btn("خروج").apply{setOnClickListener{scope.launch{try{withTimeout(5000){ncSupabase.auth.signOut()}}catch(_:Exception){};uid=null;username="";premium=false;showAuth()}}});root.addView(h,lp(-1,0,10));root.addView(t("سلام $username 👋",19f,true),lp(-1,0,10));val search=inp("جستجوی گفتگو یا نام کاربری");root.addView(search,lp(-1,0,8));val start=btn("＋ شروع گفتگوی جدید");root.addView(start,lp(-1,0,14));start.setOnClickListener{startChatByUsername(search,start)};root.addView(t("گفتگوهای من",19f,true),lp(-1,0,8));val sv=ScrollView(this);val rows=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL};sv.addView(rows);root.addView(sv,LinearLayout.LayoutParams(-1,0,1f));list=rows;setContentView(root);search.addTextChangedListener(object:TextWatcher{override fun beforeTextChanged(s:CharSequence?,a:Int,b:Int,c:Int)=Unit;override fun onTextChanged(s:CharSequence?,a:Int,b:Int,c:Int){renderConversations(rows,s?.toString().orEmpty())};override fun afterTextChanged(e:Editable?)=Unit});scope.launch{loadConversations(rows)};startHomeRealtime()}
 private fun startChatByUsername(input:EditText,button:Button){val u=input.text.toString().trim().lowercase(Locale.ROOT);if(!u.matches(Regex("[a-z0-9_]{2,30}"))){input.error="نام کاربری معتبر نیست";return};button.isEnabled=false;scope.launch{try{val target=withTimeout(10000){ncSupabase.from("profiles").select{filter{eq("username",u)}}.decodeSingleOrNull<NCProfile>()}?:error("کاربر پیدا نشد");val me=uid?:error("جلسه وجود ندارد");if(target.id==me)error("گفتگو با خودت ممکن نیست");val cid=withTimeout(10000){ncSupabase.postgrest.rpc("create_direct_conversation",CreateConversationParams(target.id)).decodeAs<String>()};activeCid=cid;chatUser=target.username;showChat()}catch(e:Exception){Toast.makeText(this@NimChatActivity,friendly(e),Toast.LENGTH_LONG).show()}finally{button.isEnabled=true}}}
 private suspend fun loadConversations(c:LinearLayout){try{cachedConversations=withTimeout(12000){ncSupabase.postgrest.rpc("list_my_conversations").decodeList<NCConversation>()};val totalUnread=cachedConversations.sumOf{it.unread_count};val previous=lastUnreadTotal;lastUnreadTotal=totalUnread;renderConversations(c,"");if(previous!=null&&totalUnread>previous&&activeCid==null)notifyIncoming()}catch(e:Exception){c.removeAllViews();c.addView(t("بارگذاری ناموفق",14f),lp(-1,10))}}
 private fun renderConversations(c:LinearLayout,raw:String){val q=raw.trim().lowercase(Locale.ROOT);val rows=cachedConversations.filter{r->q.isBlank()||r.other_username.lowercase(Locale.ROOT).contains(q)||r.other_display_name.orEmpty().lowercase(Locale.ROOT).contains(q)||r.last_message.orEmpty().lowercase(Locale.ROOT).contains(q)};c.removeAllViews();if(rows.isEmpty()){c.addView(t(if(q.isBlank())"هنوز گفتگویی نداری." else "نتیجه‌ای پیدا نشد",15f),lp(-1,10));return};rows.forEach{r->val item=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(14,12,14,12);setBackgroundColor(Color.WHITE)};item.addView(t(r.other_display_name?.takeIf{it.isNotBlank()}?:r.other_username,17f,true));item.addView(t(r.last_message?.take(80)?:"هنوز پیامی ارسال نشده",14f),lp(-1,4));if(r.unread_count>0)item.addView(t("خوانده‌نشده: ${r.unread_count}",12f,true),lp(-1,4));item.setOnClickListener{activeCid=r.conversation_id;chatUser=r.other_username;showChat()};c.addView(item,lp(-1,0,8))}}
 private fun showChat(){val cid=activeCid?:return;stopChatOnly();val root=base();val h=LinearLayout(this).apply{gravity=Gravity.CENTER_VERTICAL};val back=btn("‹");h.addView(back);h.addView(t(chatUser,22f,true),LinearLayout.LayoutParams(0,-2,1f));val attach=btn("📎");h.addView(attach);back.setOnClickListener{showHome()};attach.setOnClickListener{pickAttachment(cid)};root.addView(h,lp(-1,0,6));val sv=ScrollView(this);val messages=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL};sv.addView(messages);root.addView(sv,LinearLayout.LayoutParams(-1,0,1f));list=messages;scroll=sv;val composer=LinearLayout(this);val input=inp("پیام بنویس...").apply{maxLines=4};val send=btn("ارسال");composer.addView(input,LinearLayout.LayoutParams(0,-2,1f));composer.addView(send);root.addView(composer,lp(-1,8));setContentView(root);send.setOnClickListener{sendText(cid,input,send)};scope.launch{refreshMessages(cid)};startChatRealtime(cid)}
 private fun sendText(cid:String,input:EditText,button:Button){val body=input.text.toString().trim();if(body.isEmpty())return;if(body.length>4000){input.error="حداکثر ۴۰۰۰ کاراکتر";return};button.isEnabled=false;scope.launch{val me=uid;if(me==null){button.isEnabled=true;return@launch};val id=UUID.randomUUID().toString();try{sendOutgoing(NCMessage(id,cid,me,body));input.text.clear();failedOutgoing.remove(id);outbox.remove(id);refreshMessages(cid)}catch(e:Exception){val f=NCFailedMessage(id,cid,me,body,friendly(e));failedOutgoing[id]=f;outbox.save(f);refreshMessages(cid)}finally{button.isEnabled=true}}}
 private suspend fun sendOutgoing(m:NCMessage){try{withTimeout(10000){ncSupabase.from("messages").insert(m)}}catch(primary:Exception){val id=m.id;if(id!=null){val existing=runCatching{withTimeout(5000){ncSupabase.from("messages").select{filter{eq("id",id)}}.decodeSingleOrNull<NCMessage>()}}.getOrNull();if(existing!=null)return};throw primary}}
 private fun retryFailedMessage(f:NCFailedMessage){if(!NimChatRetry.shouldRetry(f,activeCid?:return))return;scope.launch{try{val me=uid?:return@launch;sendOutgoing(NCMessage(f.id,f.conversation_id,me,f.body));failedOutgoing.remove(f.id);outbox.remove(f.id);refreshMessages(f.conversation_id)}catch(e:Exception){outbox.save(f.copy(error=friendly(e)))}}}
 private fun startChatRealtime(cid:String){rt=scope.launch{try{ncSupabase.realtime.connect();val ch=ncSupabase.realtime.channel("chat-"+cid);chatChannel=ch;val a=ch.postgresChangeFlow<PostgresAction.Insert>(schema="public"){table="messages";eq("conversation_id",cid)};val b=ch.postgresChangeFlow<PostgresAction.Update>(schema="public"){table="messages";eq("conversation_id",cid)};val d=ch.postgresChangeFlow<PostgresAction.Delete>(schema="public"){table="messages";eq("conversation_id",cid)};ch.subscribe();merge(a,b,d).collect{queueRefresh(cid)}}catch(_:Exception){}};fallback=scope.launch{while(isActive){delay(6000);if(activeCid==cid)refreshMessages(cid)}}}
 private fun queueRefresh(cid:String){if(refreshQueued)return;refreshQueued=true;scope.launch{delay(150);refreshQueued=false;if(activeCid==cid)refreshMessages(cid)}}
 private suspend fun refreshMessages(cid:String){try{var ms=withTimeout(10000){ncSupabase.from("messages").select{filter{eq("conversation_id",cid)};order("created_at",Order.ASCENDING)}.decodeList<NCMessage>()};if(ms.any{it.sender_id!=uid&&it.read_at==null}){withTimeout(10000){ncSupabase.postgrest.rpc("mark_conversation_read",MarkConversationReadParams(cid))};ms=withTimeout(10000){ncSupabase.from("messages").select{filter{eq("conversation_id",cid)};order("created_at",Order.ASCENDING)}.decodeList<NCMessage>()}};val c=list?:return;failedOutgoing.clear();outbox.loadForConversation(cid).forEach{failedOutgoing[it.id]=it};c.removeAllViews();ms.forEach{addMessage(c,it)};failedOutgoing.values.forEach{if(NimChatRetry.shouldRetry(it,cid))addFailedMessage(c,it)};scroll?.post{scroll?.fullScroll(View.FOCUS_DOWN)}}catch(_:Exception){}}
 private fun addFailedMessage(p:LinearLayout,f:NCFailedMessage){val box=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(12,8,12,8);setBackgroundColor(Color.rgb(255,235,235))};box.addView(t(f.body,16f));box.addView(t("ارسال نشد: ${f.error}",11f));box.addView(btn("تلاش مجدد").apply{setOnClickListener{retryFailedMessage(f)}});p.addView(box,lp(-1,4))}
 private fun addMessage(p:LinearLayout,m:NCMessage){val mine=m.sender_id==uid;val row=LinearLayout(this).apply{gravity=if(mine)Gravity.END else Gravity.START};val box=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(12,8,12,8);setBackgroundColor(if(mine)Color.rgb(220,235,255)else Color.WHITE)};if(!m.body.isNullOrBlank())box.addView(t(m.body.orEmpty(),16f));if(m.attachment_path!=null){val fileButton=btn("📎 ${m.attachment_name?:"فایل"}");fileButton.setOnClickListener{openAttachment(m)};box.addView(fileButton,lp(-1,4));if(m.attachment_mime?.startsWith("image/")==true){val image=ImageView(this).apply{adjustViewBounds=true;maxHeight=600};box.addView(image,lp(-1,4));scope.launch{try{val temp=File(cacheDir,"preview_${m.id}.img");withContext(Dispatchers.IO){ncSupabase.storage.from("chat-files").downloadAuthenticatedTo(m.attachment_path,temp)};image.setImageBitmap(BitmapFactory.decodeFile(temp.absolutePath));temp.delete()}catch(_:Exception){}}}};box.addView(t(if(mine&&m.read_at!=null)"✓✓ خوانده شد" else formatTime(m.created_at),10f));if(mine)box.setOnLongClickListener{messageActions(m);true};row.addView(box);p.addView(row,lp(-1,3))}
 private fun messageActions(m:NCMessage){val editable=!m.body.isNullOrBlank();val options=if(editable)arrayOf("ویرایش پیام","حذف پیام","لغو")else arrayOf("حذف پیام","لغو");AlertDialog.Builder(this).setItems(options){_,which->when{editable&&which==0->editMessage(m);editable&&which==1->confirmDelete(m);!editable&&which==0->confirmDelete(m)}}.show()}
 private fun editMessage(m:NCMessage){val input=inp("متن جدید").apply{setText(m.body.orEmpty());maxLines=6};AlertDialog.Builder(this).setTitle("ویرایش پیام").setView(input).setNegativeButton("لغو",null).setPositiveButton("ذخیره"){_,_->scope.launch{try{val body=input.text.toString().trim();if(body.isEmpty())return@launch;if(body.length>4000)error("حداکثر ۴۰۰۰ کاراکتر");withTimeout(10000){ncSupabase.from("messages").update({set("body",body)}){filter{eq("id",m.id?:"")}}};activeCid?.let{refreshMessages(it)}}catch(e:Exception){Toast.makeText(this@NimChatActivity,friendly(e),Toast.LENGTH_LONG).show()}}}.show()}
 private fun confirmDelete(m:NCMessage){AlertDialog.Builder(this).setTitle("حذف پیام").setMessage("این پیام حذف شود؟").setNegativeButton("لغو",null).setPositiveButton("حذف"){_,_->scope.launch{try{withTimeout(10000){ncSupabase.from("messages").delete{filter{eq("id",m.id?:"")}}};if(m.attachment_path!=null)runCatching{withTimeout(10000){ncSupabase.storage.from("chat-files").delete(m.attachment_path)}};activeCid?.let{refreshMessages(it)}}catch(e:Exception){Toast.makeText(this@NimChatActivity,friendly(e),Toast.LENGTH_LONG).show()}}}.show()}
 private fun pickAttachment(cid:String){pendingAttachmentConversation=cid;startActivityForResult(Intent(Intent.ACTION_OPEN_DOCUMENT).apply{type="*/*";addCategory(Intent.CATEGORY_OPENABLE)},pickFile)}
 private var pendingAttachmentConversation:String?=null
 override fun onActivityResult(requestCode:Int,resultCode:Int,data:Intent?){super.onActivityResult(requestCode,resultCode,data);if(requestCode!=pickFile||resultCode!=RESULT_OK)return;val uri=data?.data?:return;val cid=pendingAttachmentConversation?:return;pendingAttachmentConversation=null;scope.launch{try{uploadAttachment(cid,uri)}catch(e:Exception){Toast.makeText(this@NimChatActivity,"فایل ارسال نشد: ${friendly(e)}",Toast.LENGTH_LONG).show()}}}
 private suspend fun uploadAttachment(cid:String,uri:Uri){val me=uid?:error("جلسه وجود ندارد");val name=queryName(uri)?.take(120)?:"attachment";val mime=contentResolver.getType(uri)?:"application/octet-stream";val file=withContext(Dispatchers.IO){NCFeatureHelpers.copyUriToCache(this@NimChatActivity,uri,name,mime,premium)};var uploadedPath:String?=null;try{val path="$me/$cid/${UUID.randomUUID()}_${file.name.substringAfterLast('_').take(120)}";uploadedPath=path;val bucket=ncSupabase.storage.from("chat-files");val upload=bucket.createOrContinueUpload(path,file);withTimeout(6*60*60*1000L){upload.startOrResumeUploading()};withTimeout(10000){ncSupabase.from("messages").insert(NCMessage(UUID.randomUUID().toString(),cid,me,null,attachment_path=path,attachment_name=name,attachment_mime=mime,attachment_size=file.length()))};refreshMessages(cid)}catch(e:Exception){if(uploadedPath!=null)runCatching{withTimeout(10000){ncSupabase.storage.from("chat-files").delete(uploadedPath!!)}};throw e}finally{file.delete()}}
 private fun queryName(u:Uri):String?=contentResolver.query(u,arrayOf(OpenableColumns.DISPLAY_NAME),null,null,null)?.use{if(it.moveToFirst())it.getString(0)else null}
 private fun openAttachment(m:NCMessage){scope.launch{try{val safe=(m.attachment_name?:"download").replace(Regex("[^A-Za-z0-9._-]"),"_").take(120);val file=File(cacheDir,"open_${System.currentTimeMillis()}_$safe");withContext(Dispatchers.IO){withTimeout(10*60*60*1000L){ncSupabase.storage.from("chat-files").downloadAuthenticatedTo(m.attachment_path!!,file)}};val uri=FileProvider.getUriForFile(this@NimChatActivity,"$packageName.fileprovider",file);startActivity(Intent(Intent.ACTION_VIEW).apply{setDataAndType(uri,m.attachment_mime?:"application/octet-stream");addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)})}catch(e:Exception){Toast.makeText(this@NimChatActivity,"باز کردن فایل ناموفق: ${friendly(e)}",Toast.LENGTH_LONG).show()}}}
 private fun showProfileDialog(){val field=inp("نام نمایشی");field.setText(username);val d=AlertDialog.Builder(this).setTitle("پروفایل").setView(field).setNegativeButton("لغو",null).setPositiveButton("ذخیره",null).create();d.setOnShowListener{d.getButton(AlertDialog.BUTTON_POSITIVE).setOnClickListener{val id=uid?:return@setOnClickListener;scope.launch{try{ncSupabase.from("profiles").update({set("display_name",field.text.toString().trim())}){filter{eq("id",id)}};d.dismiss();showHome()}catch(e:Exception){Toast.makeText(this@NimChatActivity,friendly(e),Toast.LENGTH_LONG).show()}}}};d.show()}
 private fun startHomeRealtime(){if(homeRt?.isActive==true)return;homeRt=scope.launch{try{ncSupabase.realtime.connect();val id=uid?:return@launch;val ch=ncSupabase.realtime.channel("home-"+id);homeChannel=ch;val a=ch.postgresChangeFlow<PostgresAction.Insert>(schema="public"){table="messages"};val b=ch.postgresChangeFlow<PostgresAction.Update>(schema="public"){table="messages"};ch.subscribe();merge(a,b).collect{val c=list;if(c!=null)loadConversations(c)}}catch(_:Exception){}}}
 private fun notifyIncoming(){if(activeCid!=null)return;if(Build.VERSION.SDK_INT>=33&&checkSelfPermission(Manifest.permission.POST_NOTIFICATIONS)!=PackageManager.PERMISSION_GRANTED){ActivityCompat.requestPermissions(this,arrayOf(Manifest.permission.POST_NOTIFICATIONS),77);return};try{val n=NotificationCompat.Builder(this,channelId).setSmallIcon(android.R.drawable.ic_dialog_email).setContentTitle("پیام جدید در NimChat").setContentText("یک پیام جدید دریافت شد").setAutoCancel(true).setPriority(NotificationCompat.PRIORITY_DEFAULT).build();NotificationManagerCompat.from(this).notify((System.currentTimeMillis()%100000).toInt(),n)}catch(_:Exception){}}
 private fun createNotificationChannel(){if(Build.VERSION.SDK_INT>=26)getSystemService(NotificationManager::class.java).createNotificationChannel(NotificationChannel(channelId,"NimChat",NotificationManager.IMPORTANCE_DEFAULT))}
 private fun stopChatOnly(){rt?.cancel();fallback?.cancel();rt=null;fallback=null;refreshQueued=false;val ch=chatChannel;chatChannel=null;if(ch!=null)try{ncSupabase.realtime.removeChannel(ch)}catch(_:Exception){}}
 private fun stopAll(){stopChatOnly();homeRt?.cancel();homeRt=null;val ch=homeChannel;homeChannel=null;if(ch!=null)try{ncSupabase.realtime.removeChannel(ch)}catch(_:Exception){};try{ncSupabase.realtime.removeAllChannels()}catch(_:Exception){}}
 private fun friendly(e:Exception):String{val m=e.message;return if(m==null)"خطای نامشخص" else m.replace("\n"," ").take(220)}
 private fun formatTime(v:String?):String{if(v.isNullOrBlank())return "";val p=v.indexOf('T');return if(p>=0&&v.length>p+5)v.substring(p+1,p+6)else v.take(16)}
}