package com.nimchat.app

import android.Manifest
import android.app.*
import android.content.*
import android.content.pm.PackageManager
import android.graphics.Color
import android.graphics.Typeface
import android.os.Build
import android.os.Bundle
import android.text.Editable
import android.text.TextWatcher
import android.view.*
import android.view.inputmethod.EditorInfo
import android.widget.*
import androidx.core.app.ActivityCompat
import androidx.core.app.NotificationCompat
import androidx.core.app.NotificationManagerCompat
import io.github.jan.supabase.auth.Auth
import io.github.jan.supabase.auth.auth
import io.github.jan.supabase.auth.signInAnonymously
import io.github.jan.supabase.createSupabaseClient
import io.github.jan.supabase.postgrest.Postgrest
import io.github.jan.supabase.postgrest.from
import io.github.jan.supabase.postgrest.query.Order
import io.github.jan.supabase.realtime.PostgresAction
import io.github.jan.supabase.realtime.Realtime
import io.github.jan.supabase.storage.Storage
import kotlinx.coroutines.*
import kotlinx.coroutines.flow.merge
import kotlinx.serialization.Serializable
import java.util.*

@Serializable data class NCProfile(val id:String,val username:String,val display_name:String?=null)
@Serializable data class NCMessage(val id:String?=null,val conversation_id:String,val sender_id:String,val body:String?=null,val created_at:String?=null,val updated_at:String?=null,val read_at:String?=null,val attachment_path:String?=null,val attachment_name:String?=null,val attachment_mime:String?=null,val attachment_size:Long?=null)
@Serializable data class NCConversation(val conversation_id:String,val other_user_id:String,val other_username:String,val other_display_name:String?=null,val last_message:String?=null,val last_message_at:String?=null,val unread_count:Long=0)
private val ncSupabase=createSupabaseClient(BuildConfig.SUPABASE_URL,BuildConfig.SUPABASE_KEY){install(Auth);install(Postgrest);install(Realtime);install(Storage)}

class NimChatActivity:Activity(){
 private val scope=CoroutineScope(SupervisorJob()+Dispatchers.Main);private val outbox by lazy{NCOutbox(getSharedPreferences("nimchat_outbox",MODE_PRIVATE))}
 private var uid:String?=null;private var username="";private var activeCid:String?=null;private var chatUser="";private var list:LinearLayout?=null;private var scroll:ScrollView?=null;private var rt:Job?=null;private var homeRt:Job?=null;private var fallback:Job?=null;private var cachedConversations=emptyList<NCConversation>();private val failedOutgoing=linkedMapOf<String,NCFailedMessage>();private var refreshQueued=false;private val channelId="nimchat_messages"
 override fun onCreate(s:Bundle?){super.onCreate(s);createNotificationChannel();uid=ncSupabase.auth.currentUserOrNull()?.id;if(uid==null)showAuth()else loadProfile()}
 override fun onDestroy(){stopAll();scope.cancel();super.onDestroy()}
 private fun base()=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(20,20,20,16);setBackgroundColor(Color.rgb(248,249,251))}
 private fun t(s:String,z:Float,b:Boolean=false)=TextView(this).apply{text=s;textSize=z;if(b)typeface=Typeface.DEFAULT_BOLD}
 private fun btn(s:String)=Button(this).apply{text=s;isAllCaps=false}
 private fun inp(h:String)=EditText(this).apply{hint=h;textSize=16f;maxLines=1;imeOptions=EditorInfo.IME_ACTION_DONE}
 private fun lp(w:Int=-1,top:Int=0,bottom:Int=0)=LinearLayout.LayoutParams(w,LinearLayout.LayoutParams.WRAP_CONTENT).apply{setMargins(0,top,0,bottom)}
 private fun showAuth(error:String?=null){stopAll();val root=base();root.gravity=Gravity.CENTER_HORIZONTAL;root.addView(t("NimChat",34f,true),lp());root.addView(t("پیام‌رسان سریع و ساده",17f),lp(-1,8,20));if(error!=null)root.addView(t(error,14f),lp(-1,0,10));val name=inp("نام کاربری (a-z, 0-9, _)");root.addView(name,lp(-1,0,10));val enter=btn("ورود به NimChat");root.addView(enter);setContentView(root);enter.setOnClickListener{val u=name.text.toString().trim().lowercase(Locale.ROOT);if(!u.matches(Regex("[a-z0-9_]{2,30}"))){name.error="۲ تا ۳۰ کاراکتر";return@setOnClickListener};enter.isEnabled=false;scope.launch{try{val id=ensureAuthenticated();val p=withTimeout(10000){ncSupabase.from("profiles").select{filter{eq("id",id)}}.decodeSingleOrNull<NCProfile>()};if(p==null)withTimeout(10000){ncSupabase.from("profiles").insert(NCProfile(id,u,u))}else if(p.username!=u)error("نام کاربری این حساب متفاوت است");uid=id;username=u;showHome()}catch(e:Exception){enter.isEnabled=true;showAuth(friendly(e))}}}}
 private suspend fun ensureAuthenticated():String{val c=ncSupabase.auth.currentUserOrNull()?.id;if(c!=null)return c;withTimeout(12000){ncSupabase.auth.signInAnonymously()};return ncSupabase.auth.currentUserOrNull()?.id?:error("احراز هویت ناموفق")}
 private fun loadProfile()=scope.launch{try{val id=uid?:return@launch;val p=withTimeout(10000){ncSupabase.from("profiles").select{filter{eq("id",id)}}.decodeSingleOrNull<NCProfile>()};if(p==null)showAuth("پروفایل پیدا نشد")else{username=p.username;showHome()}}catch(e:Exception){showAuth(friendly(e))}}
 private fun showHome(){stopChatOnly();val root=base();val h=LinearLayout(this).apply{gravity=Gravity.CENTER_VERTICAL};h.addView(t("NimChat",28f,true),LinearLayout.LayoutParams(0,-2,1f));h.addView(btn("پروفایل").apply{setOnClickListener{showProfileDialog()}});h.addView(btn("خروج").apply{setOnClickListener{scope.launch{try{withTimeout(5000){ncSupabase.auth.signOut()}}catch(_:Exception){};uid=null;username="";showAuth()}}});root.addView(h,lp(-1,0,10));root.addView(t("سلام $username 👋",19f,true),lp(-1,0,10));val search=inp("جستجوی گفتگو یا نام کاربری");root.addView(search,lp(-1,0,8));val start=btn("＋ شروع گفتگوی جدید");root.addView(start,lp(-1,0,14));start.setOnClickListener{startChatByUsername(search,start)};root.addView(t("گفتگوهای من",19f,true),lp(-1,0,8));val sv=ScrollView(this);val rows=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL};sv.addView(rows);root.addView(sv,LinearLayout.LayoutParams(-1,0,1f));list=rows;setContentView(root);search.addTextChangedListener(object:TextWatcher{override fun beforeTextChanged(s:CharSequence?,a:Int,b:Int,c:Int)=Unit;override fun onTextChanged(s:CharSequence?,a:Int,b:Int,c:Int){renderConversations(rows,s?.toString().orEmpty())};override fun afterTextChanged(e:Editable?)=Unit});scope.launch{loadConversations(rows)};startHomeRealtime()}
 private fun startChatByUsername(input:EditText,button:Button){val u=input.text.toString().trim().lowercase(Locale.ROOT);if(!u.matches(Regex("[a-z0-9_]{2,30}"))){input.error="نام کاربری معتبر نیست";return};button.isEnabled=false;scope.launch{try{val target=withTimeout(10000){ncSupabase.from("profiles").select{filter{eq("username",u)}}.decodeSingleOrNull<NCProfile>()}?:error("کاربر پیدا نشد");val me=uid?:error("جلسه وجود ندارد");if(target.id==me)error("گفتگو با خودت ممکن نیست");val cid=withTimeout(10000){ncSupabase.postgrest.rpc("create_direct_conversation",CreateConversationParams(target.id)).decodeAs<String>()};activeCid=cid;chatUser=target.username;showChat()}catch(e:Exception){Toast.makeText(this@NimChatActivity,friendly(e),Toast.LENGTH_LONG).show()}finally{button.isEnabled=true}}}
 private suspend fun loadConversations(c:LinearLayout){try{cachedConversations=withTimeout(12000){ncSupabase.postgrest.rpc("list_my_conversations").decodeList<NCConversation>()};renderConversations(c,"")}catch(e:Exception){c.removeAllViews();c.addView(t("بارگذاری ناموفق",14f),lp(-1,10))}}
 private fun renderConversations(c:LinearLayout,raw:String){val q=raw.trim().lowercase(Locale.ROOT);val rows=cachedConversations.filter{r->q.isBlank()||r.other_username.lowercase(Locale.ROOT).contains(q)||r.other_display_name.orEmpty().lowercase(Locale.ROOT).contains(q)||r.last_message.orEmpty().lowercase(Locale.ROOT).contains(q)};c.removeAllViews();if(rows.isEmpty()){c.addView(t(if(q.isBlank())"هنوز گفتگویی نداری." else "نتیجه‌ای پیدا نشد",15f),lp(-1,10));return};rows.forEach{r->val item=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(14,12,14,12);setBackgroundColor(Color.WHITE)};item.addView(t(r.other_display_name?.takeIf{it.isNotBlank()}?:r.other_username,17f,true));item.addView(t(r.last_message?.take(80)?:"هنوز پیامی ارسال نشده",14f),lp(-1,4));if(r.unread_count>0)item.addView(t("خوانده‌نشده: ${r.unread_count}",12f,true),lp(-1,4));item.setOnClickListener{activeCid=r.conversation_id;chatUser=r.other_username;showChat()};c.addView(item,lp(-1,0,8))}}
 private fun showChat(){val cid=activeCid?:return;stopChatOnly();val root=base();val h=LinearLayout(this).apply{gravity=Gravity.CENTER_VERTICAL};val back=btn("‹");h.addView(back);h.addView(t(chatUser,22f,true),LinearLayout.LayoutParams(0,-2,1f));back.setOnClickListener{showHome()};root.addView(h,lp(-1,0,6));val sv=ScrollView(this);val messages=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL};sv.addView(messages);root.addView(sv,LinearLayout.LayoutParams(-1,0,1f));list=messages;scroll=sv;val composer=LinearLayout(this);val input=inp("پیام بنویس...").apply{maxLines=4};val send=btn("ارسال");composer.addView(input,LinearLayout.LayoutParams(0,-2,1f));composer.addView(send);root.addView(composer,lp(-1,8));setContentView(root);send.setOnClickListener{sendText(cid,input,send)};scope.launch{refreshMessages(cid)};startChatRealtime(cid)}
 private fun sendText(cid:String,input:EditText,button:Button){val body=input.text.toString().trim();if(body.isEmpty())return;if(body.length>4000){input.error="حداکثر ۴۰۰۰ کاراکتر";return};button.isEnabled=false;scope.launch{val me=uid;if(me==null){button.isEnabled=true;return@launch};val id=UUID.randomUUID().toString();try{sendOutgoing(NCMessage(id,cid,me,body));input.text.clear();failedOutgoing.remove(id);outbox.remove(id);refreshMessages(cid)}catch(e:Exception){val f=NCFailedMessage(id,cid,me,body,friendly(e));failedOutgoing[id]=f;outbox.save(f);refreshMessages(cid)}finally{button.isEnabled=true}}}
 private suspend fun sendOutgoing(m:NCMessage){withTimeout(10000){ncSupabase.from("messages").insert(m)}}
 private fun retryFailedMessage(f:NCFailedMessage){if(!NimChatRetry.shouldRetry(f,activeCid?:return))return;scope.launch{try{val me=uid?:return@launch;sendOutgoing(NCMessage(f.id,f.conversation_id,me,f.body));failedOutgoing.remove(f.id);outbox.remove(f.id);refreshMessages(f.conversation_id)}catch(e:Exception){outbox.save(f.copy(error=friendly(e)))}}}
 private fun startChatRealtime(cid:String){rt=scope.launch{try{ncSupabase.realtime.connect();val ch=ncSupabase.realtime.channel("chat-"+cid);val a=ch.postgresChangeFlow<PostgresAction.Insert>(schema="public"){table="messages"};val b=ch.postgresChangeFlow<PostgresAction.Update>(schema="public"){table="messages"};val d=ch.postgresChangeFlow<PostgresAction.Delete>(schema="public"){table="messages"};ch.subscribe();merge(a,b,d).collect{queueRefresh(cid)}}catch(_:Exception){}};fallback=scope.launch{while(isActive){delay(6000);if(activeCid==cid)refreshMessages(cid)}}}
 private fun queueRefresh(cid:String){if(refreshQueued)return;refreshQueued=true;scope.launch{delay(150);refreshQueued=false;if(activeCid==cid)refreshMessages(cid)}}
 private suspend fun refreshMessages(cid:String){try{var ms=withTimeout(10000){ncSupabase.from("messages").select{filter{eq("conversation_id",cid)};order("created_at",Order.ASCENDING)}.decodeList<NCMessage>()};if(ms.any{it.sender_id!=uid&&it.read_at==null}){withTimeout(10000){ncSupabase.postgrest.rpc("mark_conversation_read",MarkConversationReadParams(cid))};ms=withTimeout(10000){ncSupabase.from("messages").select{filter{eq("conversation_id",cid)};order("created_at",Order.ASCENDING)}.decodeList<NCMessage>()}};val c=list?:return;failedOutgoing.clear();outbox.loadForConversation(cid).forEach{failedOutgoing[it.id]=it};c.removeAllViews();ms.forEach{addMessage(c,it)};failedOutgoing.values.forEach{if(NimChatRetry.shouldRetry(it,cid))addFailedMessage(c,it)};scroll?.post{scroll?.fullScroll(View.FOCUS_DOWN)}}catch(_:Exception){}}
 private fun addFailedMessage(p:LinearLayout,f:NCFailedMessage){val box=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(12,8,12,8);setBackgroundColor(Color.rgb(255,235,235))};box.addView(t(f.body,16f));box.addView(t("ارسال نشد: ${f.error}",11f));box.addView(btn("تلاش مجدد").apply{setOnClickListener{retryFailedMessage(f)}});p.addView(box,lp(-1,4))}
 private fun addMessage(p:LinearLayout,m:NCMessage){val mine=m.sender_id==uid;val row=LinearLayout(this).apply{gravity=if(mine)Gravity.END else Gravity.START};val box=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(12,8,12,8);setBackgroundColor(if(mine)Color.rgb(220,235,255)else Color.WHITE)};if(!m.body.isNullOrBlank())box.addView(t(m.body!!,16f));box.addView(t(if(m.read_at!=null&&mine)"✓✓ خوانده شد" else formatTime(m.created_at),10f));if(mine)box.setOnLongClickListener{messageActions(m);true};row.addView(box);p.addView(row,lp(-1,3))}
 private fun messageActions(m:NCMessage){AlertDialog.Builder(this).setItems(arrayOf("حذف پیام","لغو")){_,w->if(w==0)confirmDelete(m)}.show()}
 private fun confirmDelete(m:NCMessage){AlertDialog.Builder(this).setTitle("حذف پیام").setMessage("این پیام حذف شود؟").setNegativeButton("لغو",null).setPositiveButton("حذف"){_,_->scope.launch{try{ncSupabase.from("messages").delete{filter{eq("id",m.id?:"")}};activeCid?.let{refreshMessages(it)}}catch(_:Exception){}}}.show()}
 private fun showProfileDialog(){val field=inp("نام نمایشی");field.setText(username);val d=AlertDialog.Builder(this).setTitle("پروفایل").setView(field).setNegativeButton("لغو",null).setPositiveButton("ذخیره",null).create();d.setOnShowListener{d.getButton(AlertDialog.BUTTON_POSITIVE).setOnClickListener{val id=uid?:return@setOnClickListener;scope.launch{try{ncSupabase.from("profiles").update({set("display_name",field.text.toString().trim())}){filter{eq("id",id)}};d.dismiss();showHome()}catch(e:Exception){Toast.makeText(this@NimChatActivity,friendly(e),Toast.LENGTH_LONG).show()}}}};d.show()}
 private fun startHomeRealtime(){homeRt=scope.launch{try{ncSupabase.realtime.connect();val id=uid?:"user";val ch=ncSupabase.realtime.channel("home-"+id);val a=ch.postgresChangeFlow<PostgresAction.Insert>(schema="public"){table="messages"};val b=ch.postgresChangeFlow<PostgresAction.Update>(schema="public"){table="messages"};ch.subscribe();merge(a,b).collect{val c=list;if(c!=null)loadConversations(c)}}catch(_:Exception){}}}
 private fun createNotificationChannel(){if(Build.VERSION.SDK_INT>=26){getSystemService(NotificationManager::class.java).createNotificationChannel(NotificationChannel(channelId,"NimChat",NotificationManager.IMPORTANCE_DEFAULT))}}
 private fun stopChatOnly(){rt?.cancel();fallback?.cancel();rt=null;fallback=null;refreshQueued=false;try{ncSupabase.realtime.removeAllChannels()}catch(_:Exception){}}
 private fun stopAll(){stopChatOnly();homeRt?.cancel();homeRt=null;try{ncSupabase.realtime.removeAllChannels()}catch(_:Exception){}}
 private fun friendly(e:Exception)=e.message?.take(220)?:"خطای نامشخص"
 private fun formatTime(v:String?):String{if(v.isNullOrBlank())return"";val p=v.indexOf('T');return if(p>=0&&v.length>p+5)v.substring(p+1,p+6)else v.take(16)}
}
